name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git (checkout to main)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup git
        run: |
          git config --local user.name valflrt
          git config --local user.email vfleurit@gmail.com
          git config --local advice.addIgnoredFile false

      - name: Build
        run: |
          npm install
          npm run build

      - name: Push changes to `main` branch
        run: |
          git add *
          git stage *
          git commit -m "Automated build"
          git push

      - name: Checkout to `build` branch
        run: |
          git checkout -B build

      - name: Remove useless files and folders (`build` branch)
        run: rm -rf ./src/ ./node_modules/ ./README.md tsconfig.json ./.github ./.vscode ./.gitignore

      - name: Push changes to `build` branch
        run: |
          git add *
          git stage *
          git commit -m "Automated build"
          git push
